---
- hosts: all
  tags: ['primary', 'secondary']
  gather_facts: yes

- hosts: all
  sudo: yes
  gather_facts: no
  roles:
    - common

- hosts: primary
  gather_facts: no
  become: yes
  become_user: postgres
  roles:
    - { role: primary, tags: ['primary'] }

- hosts: secondary
  gather_facts: no
  become: yes
  become_user: postgres
  roles:
    - { role: secondary, tags: ['secondary'] }
