- name: initdb
  command: "{{ initdb[ansible_distribution_major_version] }} creates={{ dbpath }}/PG_VERSION"
  sudo: yes
  sudo_user: root

- name: Template postgres.conf and pg_hba.conf
  template:
    src: '{{ item }}.conf.j2'
    dest: '{{ dbpath }}/{{item }}.conf'
  with_items:
    - postgresql
    - pg_hba
  register: pg_config

- name: Ensure pgsql service is started
  become: yes
  become_user: root
  service:
    name: postgresql-9.4
    state: restarted
    enabled: true
  when: pg_config|changed

# - name: Create encrypted password
#   shell: echo -n {{ pw }}{{ dbuser }} | /usr/bin/openssl dgst -md5
#   register: towerpw

# - name: Create encrypted repl password
#   shell: echo -n {{ repl_pw }}repl | /usr/bin/openssl dgst -md5
#   register: replpw

- name: Ensure DB user exists
  postgresql_user:
    name: "{{ dbuser }}"
    password: '{{ pw }}'
  no_log: true

- name: Ensure replication user exists
  postgresql_user:
    name: repl
    role_attr_flags: "LOGIN,REPLICATION"
    password: "{{ repl_pw }}"

- name: Ensure Tower DB exists
  postgresql_db:
    name: "{{ dbname }}"
    owner: "{{ dbuser }}"




